backend:
  name: github
  repo: nasradeentaher/Professional-Profile
  branch: main

# مكان حفظ الصور
media_folder: "images/uploads"
public_folder: "/images/uploads"

# اللغة
locale: "ar"

collections:
  - name: "products"
    label: "المنتجات"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "اسم المنتج", name: "title", widget: "string" }
      - { label: "السعر", name: "price", widget: "number" }
      - { label: "الوصف", name: "body", widget: "markdown" }
      - { label: "صورة المنتج", name: "image", widget: "image", required: false }
